name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: devops-app

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'   # use '16' if you must
          cache: 'npm'
          cache-dependency-path: devops-app/package-lock.json
      - run: npm ci
      - run: npm test -- --watchAll=false
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: devops-app/build